[project]
name = "styled-prose"
version = "0.1.0"
description = "Convert prose to images using discrete bitmap transformations."
authors = [
    {name = "thearchitector", email = "me@eliasfgabriel.com"},
]
readme = "README.md"
license = {text = "MIT"}

requires-python = ">=3.8"
dependencies = [
    "reportlab>=4.0.0",
    "pydantic>=2.0.0",
    "tomli>=2.0.0 ; python_version<'3.11'",
    "httpx[http2]>=0.25.2",
]

[tool.pdm.dev-dependencies]
dev = [
    "pytest>=7.0.0",
    "mypy>=1.7.1",
]

[tool.ruff]
target-version = "py38"
extend-select = ["I", "B"]

[tool.mypy]
python_version = "3.8"
strict = true

[[tool.mypy.overrides]]
module = ["reportlab.*", "tomllib.*"]
ignore_missing_imports = true

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
